[package]
name = "http_fetcher"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.48", features = ["derive"] }
reqwest = "0.12.23"
thiserror = "2.0.16"
tokio = { version = "1.47.1", features = ["full"] }
